import type { EraId, MapDossier } from "./types";

// All nine canon dossiers. Every date, name, and number traces to
// design/RESEARCH.md; items flagged UNVERIFIED there are phrased without the
// specific claim (mirage's exact origin year, train's exact debut year).
export const maps: MapDossier[] = [
  {
    slug: "dust2",
    file: "de_dust2",
    name: "Dust II",
    era: "goldsrc",
    birthYear: "2001",
    authors: ["David “Dave” Johnston"],
    oneLiner: "The most-played competitive map ever made, and it knows it.",
    featured: true,
    lineage: [
      { year: "1999", text: "Dave Johnston’s de_dust ships with the Counter-Strike beta." },
      { year: "2001", text: "Dust II follows, adding a second bombsite and a wide-open mid." },
      { year: "2017", text: "Pulled from Active Duty, rebuilt, and returned with new textures and lighting." },
      { year: "2022", text: "Removed from Active Duty for the first time ever, replaced by Anubis before the Paris Major." },
    ],
    facts: [
      { label: "Author", value: "David “Dave” Johnston" },
      { label: "First compile", value: "March 2001" },
      { label: "Predecessor", value: "de_dust (1999)" },
      { label: "Reworks", value: "2017 texture & lighting pass" },
      { label: "Appears in", value: "1.6, Source, CS:GO, CS2" },
      { label: "Sites", value: "A (Long / Catwalk) · B (Tunnels)" },
    ],
    callouts: [
      { name: "Long A", note: "The longest sightline in the game. AWPers live here." },
      { name: "Catwalk", note: "The high road to A. Peek it early or not at all." },
      { name: "Mid Doors", note: "The double doors nobody has dared to move in twenty-five years." },
      { name: "Tunnels", note: "The dark commute to B. Bring a flash." },
      { name: "Short / Cross", note: "The gamble between mid and A. All timing." },
    ],
    moments: [
      {
        title: "Everyone’s first map",
        year: "2001",
        text: "Widely called the most-played competitive FPS map in history — the one Valve reaches for whenever a trailer needs to say “Counter-Strike” in a single image.",
      },
      {
        title: "The 2017 rework",
        year: "2017",
        text: "Valve kept the layout and rebuilt everything else. Pros argued for months about shifted sightlines on a map they’d sworn was untouchable.",
      },
      {
        title: "The changing of the guard",
        year: "2022",
        text: "For the first time since its debut, Dust II left Active Duty — bumped by Anubis, a community map, ahead of the Paris Major.",
      },
    ],
  },
  {
    slug: "mirage",
    file: "de_mirage",
    name: "Mirage",
    era: "source",
    birthYear: "mid-2000s",
    authors: ["Michael “BubkeZ” Hüll", "Valve"],
    oneLiner: "A CPL tournament map that Valve eventually made official.",
    lineage: [
      { year: "1.6 era", text: "BubkeZ builds de_cpl_strike for CPL tournaments on Counter-Strike 1.6." },
      { year: "Source era", text: "Renamed de_mirage, the map is refined across community CS:Source versions." },
      { year: "2013", text: "Valve’s official CS:GO remake ships on June 12, credited alongside the community." },
      { year: "2013–", text: "Enters Active Duty and rarely leaves — one of the pool’s most permanent fixtures." },
    ],
    facts: [
      { label: "Author", value: "Michael “BubkeZ” Hüll, with Valve" },
      { label: "Origin", value: "de_cpl_strike (CS 1.6)" },
      { label: "Official debut", value: "June 12, 2013 (CS:GO)" },
      { label: "Theme", value: "Moroccan / North-African" },
      { label: "Appears in", value: "1.6, Source, CS:GO, CS2" },
      { label: "Sites", value: "A (Palace / Ramp) · B (Apartments)" },
    ],
    callouts: [
      { name: "Palace", note: "The stone balcony over A. Owning it owns the site." },
      { name: "Jungle", note: "The bush between connector and A. Where executes are born and die." },
      { name: "Ramp", note: "The T-side on-ramp to A. Loud, exposed, unavoidable." },
      { name: "Connector", note: "The artery between mid and A. Hold it or lose the map." },
      { name: "Apartments", note: "The vertical maze into B. Bring patience." },
    ],
    moments: [
      {
        title: "The map that never leaves",
        year: "2013",
        text: "Since its 2013 debut Mirage has been one of the most consistently played Active Duty maps, rarely dropped from the pool across two engines.",
      },
      {
        title: "Jungle smoke, A execute",
        year: "2013",
        text: "The A-site “Jungle” smoke-and-execute is a staple of professional VOD reviews — the first thing new teams learn and the last thing good ones master.",
      },
    ],
  },
  {
    slug: "inferno",
    file: "de_inferno",
    name: "Inferno",
    era: "goldsrc",
    birthYear: "1999",
    authors: ["Chris “Narby” Auty"],
    oneLiner: "One choke point, endless molotovs, and a curve called Banana.",
    lineage: [
      { year: "1999", text: "Chris “Narby” Auty’s Inferno appears in an early Counter-Strike beta." },
      { year: "Source era", text: "The theme drifts from Californian mission architecture to a European village." },
      { year: "2016", text: "Valve’s rework widens Banana and Apartments and brightens the whole map." },
      { year: "2016–", text: "Survives into CS2’s Active Duty as one of the original seven." },
    ],
    facts: [
      { label: "Author", value: "Chris “Narby” Auty" },
      { label: "First compile", value: "1999 (CS beta)" },
      { label: "Reworks", value: "2016 layout-widening & lighting pass" },
      { label: "Theme", value: "European village" },
      { label: "Appears in", value: "1.6, Source, CS:GO, CS2" },
      { label: "Sites", value: "A (Arch / Library) · B (Banana)" },
    ],
    callouts: [
      { name: "Banana", note: "The famous curved choke to B. More molotovs have died here than anywhere in CS." },
      { name: "Apartments", note: "The layered route to A. Every window is a threat." },
      { name: "Second Mid", note: "The quiet middle lane. Nobody expects it until they do." },
      { name: "Arch", note: "The stone gateway onto A. A one-way argument." },
      { name: "Library", note: "The room behind A. Where lurkers go to be patient." },
    ],
    moments: [
      {
        title: "One of the original seven",
        year: "1999",
        text: "Inferno is one of a handful of maps to survive from the earliest CS betas all the way into CS2’s competitive pool — a 25-year tenure.",
      },
      {
        title: "The most-studied choke in CS",
        year: "2016",
        text: "Banana is the subject of countless incendiary-lineup guides. Whole rounds are decided by who controls a curved dirt path barely two players wide.",
      },
    ],
  },
  {
    slug: "nuke",
    file: "de_nuke",
    name: "Nuke",
    era: "goldsrc",
    birthYear: "1999",
    authors: ["Jo Bieg"],
    oneLiner: "Two bombsites stacked on top of each other. Verticality, weaponized.",
    lineage: [
      { year: "1999", text: "Jo Bieg’s Nuke ships with Counter-Strike Beta 4.0." },
      { year: "Source era", text: "Ports forward through Condition Zero and CS:Source largely intact." },
      { year: "2016", text: "Valve heavily reworks the geometry and rotations around the stacked A site." },
      { year: "2016–", text: "Keeps its rare double-decker bombsite — still the pool’s most vertical map." },
    ],
    facts: [
      { label: "Author", value: "Jo Bieg" },
      { label: "First compile", value: "Beta 4.0, c. November 1999" },
      { label: "Reworks", value: "2016 geometry & rotation overhaul" },
      { label: "Signature", value: "Vertically stacked A site (Heaven / vents)" },
      { label: "Appears in", value: "1.6, Source, CS:GO, CS2" },
      { label: "Sites", value: "A (upper) · B (lower)" },
    ],
    callouts: [
      { name: "Ramp", note: "The long climb T-side takes to reach the fight. Exposed the whole way." },
      { name: "Heaven", note: "The balcony above A. The name is not ironic." },
      { name: "Secret", note: "The sneaky drop toward B. Louder than you’d like." },
      { name: "Outside", note: "The open flank around the building. A different map entirely." },
      { name: "Squeaky", note: "The door that announces you. Everyone can hear it." },
    ],
    moments: [
      {
        title: "The one vertical map",
        year: "2016",
        text: "Nuke’s double-decker bombsite — one site stacked above the other — is regularly cited by analysts as the most tactically unique layout in the competitive pool.",
      },
      {
        title: "Reworked skin, classic bones",
        year: "2016",
        text: "Despite heavy visual overhauls, Nuke stayed one of the least-changed maps by layout — proof that its strange geometry was right the first time.",
      },
    ],
  },
  {
    slug: "train",
    file: "de_train",
    name: "Train",
    era: "goldsrc",
    birthYear: "c. 2000",
    authors: ["Christopher “Warby” Mair", "Barking Dog Studios"],
    oneLiner: "A rail yard of train cars and impossibly tight angles.",
    lineage: [
      { year: "c. 2000", text: "Train appears in early Counter-Strike, built at Barking Dog Studios." },
      { year: "2014", text: "Valve rebuilds Train visually and tweaks its notoriously tight chokes." },
      { year: "2021", text: "Dropped from Active Duty in May, replaced by Ancient." },
      { year: "2024", text: "Returns November 13, rebuilt for CS2 — rainy, night-lit, and rearranged." },
    ],
    facts: [
      { label: "Author", value: "Christopher “Warby” Mair, Barking Dog Studios" },
      { label: "Reworks", value: "2014 rebuild · 2024 CS2 redesign" },
      { label: "Left Active Duty", value: "May 3, 2021" },
      { label: "Returned", value: "November 13, 2024 (CS2)" },
      { label: "Appears in", value: "1.6, Source, CS:GO, CS2" },
      { label: "Sites", value: "A & B (rail yards)" },
    ],
    callouts: [
      { name: "Ivy", note: "The leafy side route into A. Quiet until it isn’t." },
      { name: "Popdog", note: "The ladder-and-stairs connector everyone forgets to check." },
      { name: "Alley", note: "The T-side lane toward B. A commitment, not a peek." },
      { name: "Z-house", note: "The bent connector through the yard. Named for the shape you walk." },
      { name: "Main", note: "The central platform between the trains. Open, and everyone knows it." },
    ],
    moments: [
      {
        title: "Love it or hate it",
        year: "2021",
        text: "Train’s congested chokepoints made it one of the most divisive maps among pros — beloved by tacticians, cursed by anyone who had to entry it.",
      },
      {
        title: "The CS2 comeback",
        year: "2024",
        text: "Its 2024 return split opinion: Bombsite A pushed back, CT Heaven gone, fewer cars on the yard. Some pros openly weren’t sure about the new map.",
      },
    ],
  },
  {
    slug: "overpass",
    file: "de_overpass",
    name: "Overpass",
    era: "go",
    birthYear: "2013",
    authors: ["Valve"],
    oneLiner: "A Berlin canal and park, and one very famous boost.",
    lineage: [
      { year: "2013", text: "Valve introduces Overpass in December’s Winter Offensive — its first map built only for CS:GO." },
      { year: "2014", text: "The Olofboost forces a patch and an in-game sign near the spot." },
      { year: "2013–", text: "Settles in as one of the pool’s longest continuously-active maps." },
    ],
    facts: [
      { label: "Author", value: "Valve" },
      { label: "First compile", value: "December 2013 (Winter Offensive)" },
      { label: "Distinction", value: "First map built exclusively for CS:GO" },
      { label: "Theme", value: "Berlin canal & park" },
      { label: "Appears in", value: "CS:GO, CS2" },
      { label: "Sites", value: "A (Bathrooms) · B (Party)" },
    ],
    callouts: [
      { name: "Monster", note: "The pit under A. A whole gunfight happens in a hole." },
      { name: "Bathrooms", note: "The tiled approach to A. Echoes and ambushes." },
      { name: "Party", note: "The B-site plaza. Bring friends; the name is a warning." },
      { name: "Connector", note: "The pinch between the two halves of the map." },
      { name: "Fountain", note: "The T-side landmark. Where pushes gather before they go." },
    ],
    moments: [
      {
        title: "The Olofboost",
        year: "2014",
        text: "At DreamHack Winter 2014, Fnatic’s olofmeister rode a pixel-precise three-man boost onto an unintended ledge, saw half the map, and helped bury LDLC 3–12. Valve patched it.",
      },
      {
        title: "A permanent fixture",
        year: "2013",
        text: "Since its debut Overpass has been one of the longest continuously-active maps in Active Duty — a Valve original that simply never wore out.",
      },
    ],
  },
  {
    slug: "cache",
    file: "de_cache",
    name: "Cache",
    era: "source",
    birthYear: "2011",
    authors: ["Salvatore “Volcano” Garozzo", "FMPONE"],
    oneLiner: "A Chernobyl industrial zone, built by fans and bought by Valve.",
    lineage: [
      { year: "2011", text: "Salvatore “Volcano” Garozzo releases the final CS:Source version of de_cache." },
      { year: "2013", text: "FMPONE begins a full re-texture and remake for CS:GO, with Volcano’s blessing." },
      { year: "2014", text: "Added to official matchmaking in Operation Breakout." },
      { year: "2019", text: "Dropped from Active Duty in March; FMPONE rebuilds it on Source 2 after Valve acquires the map." },
    ],
    facts: [
      { label: "Author", value: "Salvatore “Volcano” Garozzo · FMPONE (remake)" },
      { label: "First compile", value: "2011 (CS:Source community)" },
      { label: "Official debut", value: "Operation Breakout, 2014" },
      { label: "Theme", value: "Industrial zone near Pripyat" },
      { label: "Appears in", value: "Source, CS:GO, CS2" },
      { label: "Sites", value: "A (Quad) · B (Boiler)" },
    ],
    callouts: [
      { name: "Squeaky", note: "The door to A that gives you away every time." },
      { name: "Quad", note: "The open A-site box. Angles in every direction." },
      { name: "Mid Doors", note: "The central crossing. Fast, loud, and often fatal." },
      { name: "Sandbags", note: "The T-side cover into A. Where the trade happens." },
      { name: "Boiler", note: "The rusted approach to B. Nowhere to hide, so don’t." },
    ],
    moments: [
      {
        title: "One of only two",
        year: "2014",
        text: "Cache is one of just two community-made maps — with Anubis — ever promoted into the official Active Duty pool. The garage build made the big leagues.",
      },
      {
        title: "The post-Soviet outlier",
        year: "2011",
        text: "Set in an industrial zone near Chernobyl’s Pripyat, Cache wears a post-Soviet grey that stands apart from the sunlit official roster around it.",
      },
    ],
  },
  {
    slug: "ancient",
    file: "de_ancient",
    name: "Ancient",
    era: "go",
    birthYear: "2020",
    authors: ["Valve"],
    oneLiner: "A jungle temple that quietly ended Train’s long reign.",
    lineage: [
      { year: "2020", text: "Valve introduces Ancient in December’s Operation Broken Fang." },
      { year: "2021", text: "Promoted to Active Duty on May 3, replacing Train — the pool’s first change in about two years." },
      { year: "2021–", text: "Carries forward into CS2’s competitive rotation." },
    ],
    facts: [
      { label: "Author", value: "Valve" },
      { label: "First compile", value: "December 4, 2020 (Broken Fang)" },
      { label: "Joined Active Duty", value: "May 3, 2021" },
      { label: "Theme", value: "Central-American jungle temple" },
      { label: "Appears in", value: "CS:GO, CS2" },
      { label: "Sites", value: "A (Ramp) · B (Cave / Donut)" },
    ],
    callouts: [
      { name: "Donut", note: "The ring-shaped cover on B. Round and round the fight goes." },
      { name: "Cave", note: "The mossy tunnel toward B. Dark, tight, decisive." },
      { name: "Ramp Room", note: "The layered climb onto A. Verticality with a view." },
      { name: "Elbow", note: "The bent connector into A. Named for the angle you clear." },
      { name: "Mid", note: "The temple’s spine. Cross it wrong and everyone sees." },
    ],
    moments: [
      {
        title: "The end of an era",
        year: "2021",
        text: "Ancient’s promotion to Active Duty in 2021 broke Train’s multi-year unbroken tenure — the first change to the competitive pool in roughly two years.",
      },
      {
        title: "Green among the grey",
        year: "2020",
        text: "A Central-American temple wrapped in jungle, Ancient’s overgrown palette stands out on a roster of mostly urban and industrial maps.",
      },
    ],
  },
  {
    slug: "anubis",
    file: "de_anubis",
    name: "Anubis",
    era: "go",
    birthYear: "2020",
    authors: ["Roald", "jakuza", "jd40"],
    oneLiner: "A contest-winning Egyptian temple that took Dust II’s seat.",
    lineage: [
      { year: "2019", text: "Roald, jakuza and jd40 win the Mapcore Mapping Contest with Anubis." },
      { year: "2020", text: "Added to CS:GO in April, moved to competitive matchmaking ten days after debut." },
      { year: "2022", text: "Returns for CS:GO’s 10th anniversary, then joins Active Duty in November — replacing Dust II." },
    ],
    facts: [
      { label: "Authors", value: "Roald, jakuza, jd40" },
      { label: "Origin", value: "Mapcore Mapping Contest 2019 winner" },
      { label: "CS:GO debut", value: "April 2020" },
      { label: "Joined Active Duty", value: "November 18, 2022" },
      { label: "Theme", value: "Egyptian temple on a canal" },
      { label: "Sites", value: "A (Palace) · B (Canal)" },
    ],
    callouts: [
      { name: "Palace", note: "The raised structure over A. Vertical power, Egyptian edition." },
      { name: "Canal", note: "The water lane splitting the map. Loud footing, no cover." },
      { name: "Connector", note: "The link between mid and the sites. Everyone funnels here." },
      { name: "Heaven", note: "The high perch on A. First to hold it usually holds the round." },
      { name: "Stairs", note: "The climb toward B. Slow, exposed, worth it." },
    ],
    moments: [
      {
        title: "The second community map",
        year: "2022",
        text: "Anubis is only the second community-made map — after Cache — ever to reach Active Duty, a quiet vote of confidence in fan mappers and the Workshop.",
      },
      {
        title: "It took Dust II’s chair",
        year: "2022",
        text: "When Anubis joined Active Duty in November 2022, it replaced Dust II — a contest-winning fan map bumping the most famous map in the game.",
      },
    ],
  },
];

export const getMap = (slug: string): MapDossier | undefined =>
  maps.find((m) => m.slug === slug);

export const mapsByEra: Record<EraId, MapDossier[]> = {
  goldsrc: maps.filter((m) => m.era === "goldsrc"),
  source: maps.filter((m) => m.era === "source"),
  go: maps.filter((m) => m.era === "go"),
  cs2: maps.filter((m) => m.era === "cs2"),
};
